stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Fake.csv
    - data_given/True.csv
    params:
    - load_data.sample_frac
    - base.random_state
    outs:
     - data/raw/news.csv

  preprocess_data:
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - data/raw/news.csv
    - src/utils
    - src/preprocess_data.py
    outs:
    - data/processed/clean_news.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - src/utils
    - data/processed/clean_news.csv
    params:
    - split_data.test_size
    - base.random_state
    outs: 
    - data/processed/train_news.csv
    - data/processed/test_news.csv

  featurize :
    cmd: python src/featurize.py --config=params.yaml
    deps: 
    - src/featurize.py
    - data/processed/train_news.csv
    - data/processed/test_news.csv
    - src/utils
    params:
    - featurize.max_features
    - featurize.n_grams
    - base.random_state
    outs:
    - data/featurized/featurized_train_news.pkl
    - data/featurized/featurized_test_news.pkl
    - saved_models/bag_of_words.pkl
    - saved_models/tfidf.pkl

  train :
    cmd: python src/train.py --config=params.yaml
    deps:
    - src/train.py
    - src/utils
    - data/featurized/featurized_train_news.pkl

    params:
    - train.n_est
    - train.n_jobs
    - train.min_split
    - base.random_state

    outs:
    - saved_models/model.pkl

  evaluate:
    cmd: python src/evaluate.py --config=params.yaml
    deps: 
     - saved_models/model.pkl
     - src/utils
     - src/evaluate.py
    metrics:
     - report/scores.json:
        cache : false   