stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Fake.csv
    - data_given/True.csv
    outs:
     - data/raw/news.csv

  preprocess_data:
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - data/raw/news.csv
    - src/preprocess_data.py
    - src
    outs:
    - data/processed/clean_news.csv