stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Fake.csv
    - data_given/True.csv
    - src
    outs:
     - data/raw/news.csv

  preprocess_data:
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - data/raw/news.csv
    - src/utils
    - src/preprocess_data.py
    outs:
    - data/processed/clean_news.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - src/utils
    - data/processed/clean_news.csv
    outs: 
    - data/processed/train_news.csv
    - data/processed/test_news.csv

  featurize :
    cmd: python src/featurize.py --config=params.yaml
    deps: 
    - src/featurize.py
    - data/processed/train_news.csv
    - data/processed/test_news.csv
    - src/utils
    outs:
    - data/featurized/featurized_train_news.pkl
    - data/featurized/featurized_test_news.pkl

  train :
    cmd: python src/train.py --config=params.yaml
    deps:
    - src/train.py
    - src/utils
    - data/featurized/featurized_train_news.pkl 
    outs:
    - saved_models/model.pkl

  evaluate:
    cmd: python src/evaluate.py --config=params.yaml
    deps: 
     - saved_models/model.pkl
     - src/utils
     - src/evaluate.py
    metrics:
     - report/scores.json:
        cache: false   