stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Fake.csv
    - data_given/True.csv
    outs:
     - data/raw/news.csv

  preprocess_data:
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - data/raw/news.csv
    - src/utils
    - src/preprocess_data.py
    outs:
    - data/processed/clean_news.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - src/utils
    - data/processed/clean_news.csv
    outs: 
    - data/processed/train_news.csv
    - data/processed/test_news.csv

  featurize :
    cmd: python src/featurize.py --config=params.yaml
    deps: 
    - src/featurize.py
    - data/processed/train_news.csv
    - data/processed/test_news.csv
    - src/utils
    outs:
    - data/featurized/featurized_train_news.pkl
    - data/featurized/featurized_test_news.pkl
    - 
