base:
  project: Fake_True_News_Classification
  random_state: 42
  #target_col: labels

data_source:
  s3_source_1: data_given/Fake.csv
  s3_source_2: data_given/True.csv

load_data:
  sample_frac: 0.1
  raw_dataset_csv: data/raw/news.csv

preprocess_data:
  clean_data: data/processed/clean_news.csv

split_data:
  train: data/processed/train_news.csv
  test: data/processed/test_news.csv
  test_size: 0.3

featurize:
  featurized_train: data/featurized/featurized_train_news.pkl
  featurized_test: data/featurized/featurized_test_news.pkl
  max_features: 2500
  n_grams: 3

train:
  model : saved_models/model.pkl
  n_est : 500
  n_jobs : 2
  min_split : 12

evaluate:
  metrics : report/scores.json
