base:
  project: Fake_True_News_Classification
  random_state: 42
  target_col: TARGET

data_source:
  s3_source_1: data_given/Fake.csv
  s3_source_2: data_given/True.csv

load_data:
  sample_frac: 0.01
  raw_dataset_csv: data/raw/news.csv

prepare_data:
  clean_data: data/processed/clean_news.csv

split_data:
  train_path: data/processed/train_news.csv
  test_path: data/processed/test_news.csv
  test_size: 0.3